dbt/include/sqlserver/macros/adapters.sql

This fix issue # 6 and cleaned up the create_table_as macro a lot.

Fix for issue #6. Cleans up old temp_relations when creating a table

---

dbt/adapters/sqlserver/connections.py

Resolves #19. I unfortunately wasn't able to test _all_ of this, as I couldn't get SQL Server running successfully on my mac. I think I'm close, but I was seeing network timeout errors when trying to connect :(
I did verify that this is valid Python code though. If anyone is able to test it out and validate that the log interpolation is working correctly, that would be awesome :)

(#19) Interpolate values in log lines

---

setup.py

Bound core imports

---

README.md
dbt/include/sqlserver/macros/adapters.sql
setup.py

Thes PR adds support for SQL Server 2012 and other older versions of SQL Server

Support for older sqlserver

---

README.md

Service principal authentication instructions were incorrect.

fixing error in README

---

.circleci/config.yml
README.md
dbt/adapters/sqlserver/connections.py
test/integration/sqlserver.dbtspec

@mikaelene approve this if you want to easily be able to test the latest PR changes I've made inside the `CI_CD_take2` branch before approving #60

Ci for sqlserver

---

dbt/include/sqlserver/macros/adapters.sql

Resolves clustered index issue on sql 2014. Does not affect whether clustered indexes are created or not

Resolves #84

---

CHANGELOG.md

add changes for v0.19.0.1

---

README.md

The first time i tried to use dbt-sqlserver, it was somewhat confusing and difficult to figure out how to make dbt-utils work.
Hopefully this will make it easier for new users.

Added info about tsql_utils to README

---

CHANGELOG.md
dbt/include/sqlserver/macros/adapters.sql
dbt/include/sqlserver/macros/materializations/snapshot/strategies.sql

When I (thought I) solved #61. I introduced a bug #108, #117. This should solve that.

Fix for bugs in snapshots

---

CHANGELOG.md
dbt/adapters/sqlserver/connections.py
dbt/include/sqlserver/macros/adapters.sql
dbt/include/sqlserver/macros/materializations/seed/seed.sql
dbt/include/sqlserver/macros/merge.sql
setup.py

fixes: #157
fixes: #161
fixes: #164
fixes: #165
also added fix for https://github.com/dbt-labs/dbt-core/pull/3510 where all the semi-colons were pulled out of the three merge statement templates.

small changes for 0.21.0

---

.circleci/config.yml

Looks like I somehow made I typo in the name of the secret as it seems to be `DBT_AZURE_SP_SECRET` instead of `DBT_AZURE_SECRET`

fix secret in circleci config

---

dbt/adapters/sqlserver/connections.py

New logging: https://github.com/dbt-labs/dbt-core/blob/v1.0.0/core/dbt/events/README.md#adapter-maintainers

New logging

---

README.md
setup.py

Help new users getting started with this repo by putting and concise information in the README and pointing to other places with centralised information like dbt docs, our contributing guide etc.

Clean-up and update README

---

dbt/include/sqlserver/macros/materializations/models/incremental/merge.sql
tests/functional/adapter/test_incremental.py

fix incremental unique array

---

dbt/include/sqlserver/macros/adapters/relation.sql
tests/functional/adapter/test_seed.py

I had to make our drop relation cascade like it does in the dbt-core implementation for this to work.

add seed tests and add cascade to drop relation

---

.github/workflows/integration-tests-azure.yml
.github/workflows/integration-tests-sqlserver.yml
.github/workflows/unit-tests.yml
Makefile
dev_requirements.txt

to be merged after https://github.com/dbt-msft/dbt-sqlserver/pull/369

make testing faster by running multithreaded

---

.git-blame-ignore-revs

add blame ignore commits

---

.pre-commit-config.yaml
dbt/__init__.py
dbt/adapters/__init__.py
dbt/include/__init__.py

Remove extra __init__.py

---

.github/workflows/integration-tests-azure.yml
.github/workflows/integration-tests-sqlserver.yml
.github/workflows/unit-tests.yml
tests/functional/adapter/test_provision_users.py

Add option to trigger CI manually

---

CHANGELOG.md
dbt/adapters/sqlserver/__version__.py

Prepare 1.4.1

---

dbt/adapters/sqlserver/sql_server_adapter.py

Adjusts the fabric version by removing syntax invalid with sqlserver

fix constraints support

---

.devcontainer/devcontainer.json
.devcontainer/setup_env.sh
.gitattributes
dbt/adapters/sqlserver/__version__.py
dbt/include/sqlserver/macros/materializations/models/table/create_table_as.sql

Fixes additional relation statement
https://github.com/dbt-msft/dbt-sqlserver/issues/488
Cleans up the devcontainer setup.
https://github.com/dbt-msft/dbt-sqlserver/issues/484

488 updates

---

dbt/adapters/sqlserver/__version__.py

Pull request for release client 1 of 1.8.0

PR for 1.8.0rc1

---

tests/functional/adapter/mssql/test_materialize_change.py

Adds test to validate behaviour of https://github.com/dbt-msft/dbt-sqlserver/issues/509 is corrected.

added test to validate swapping from table to view and view to table

---

dbt/include/sqlserver/macros/materializations/models/incremental/incremental.sql
tests/functional/adapter/mssql/test_temp_relation_cleanup.py

closes https://github.com/dbt-msft/dbt-sqlserver/issues/530
Adds logic to drop temp relations and test to validate behaviour.

added incremental fix and validation test

---

dbt/adapters/sqlserver/sqlserver_connections.py

closes https://github.com/dbt-msft/dbt-sqlserver/issues/508

update application name to app

---

dbt/include/sqlserver/macros/relations/seeds/helpers.sql
tests/functional/adapter/mssql/test_mssql_seed.py

closes https://github.com/dbt-msft/dbt-sqlserver/issues/522
Includes a test to validate load successful with a large seed file beyond the batch size.

readded batch logic and included a test

---

.github/workflows/integration-tests-sqlserver.yml
.github/workflows/unit-tests.yml

PR to add a schedule to run every sunday night

added schedule to actions

---

CHANGELOG.md
dbt/adapters/sqlserver/__version__.py

PR to bump version and add changelog.

1.8.2 Release PR

---

CHANGELOG.md
dbt/adapters/sqlserver/__version__.py

Release 1.8.3
