dbt-msft/dbt-sqlserver

README.md
I installed adapter in a Docker based on Ubuntu 18.04. Installation failed because of missing ODBC headers which pyodbc depends on. See:
https://github.com/mkleehammer/pyodbc/issues/441
=> Add note about ODBC header when installing on Ubuntu

README.md, setup.py
Added a comment on Readme and bounded the import to prevent import of 0.17 and issue of incorrectly found duplicates [issue 2423](https://github.com/fishtown-analytics/dbt/issues/2423).
Tested by locally installing inside a venv and got dbt-core 0.15.3.
=> Fixes #31. Bounded dbt core requirements for v0.15.

dbt/adapters/sqlserver/connections.py
Hi.
The previous conn_str did not handle ports different from 1433. The pyodbc.connect receive custom port like `server=ip,port` instead of `server=ip;port=port`
=> fix pyodbc connection string for custom port

dbt/adapters/sqlserver/connections.py
Referring https://github.com/mikaelene/dbt-sqlserver/issues/50
If sql server host name contains a backslash - pointing at a named instance connection to server fails
This is because if a named instance is specified, the port number must be omitted. This is fixed by checking if the specified host name contains a "\" and in that case the port number is omitted
=> added support for named instance

dbt/include/sqlserver/macros/catalog.sql
Making the fix for a breaking change from `v0.16.0` per this [Slack thread](https://getdbt.slack.com/archives/CMRMDDQ9W/p1598363160003200), to match https://github.com/fishtown-analytics/dbt/pull/2037
=> hotfix for v.0.16 change (see dbt PR #2037)

README.md, dbt/adapters/sqlserver/connections.py, setup.py
rehash of #49 but to master branch now. @nandanhegde15 will add some more documentation and test this PR does not break the existing on-prem SQL Server connection methods
=> add support for Azure SQL by adding Active Directory authentication methods

dbt/include/sqlserver/macros/adapters.sql
Fix for snapshots failing if check_cols='all' is set in config, due to default implementation of get_columns_in_query not being valid MS SQL.
=> Implement get_columns_in_query macro to fix snapshots with check_cols='all'

.circleci/config.yml, test/integration/azuresql.dbtspec, tox.ini
also test azure sql explicitly as a separate job
=> also test azure sql

test/integration/azuresql.dbtspec
we're getting [an error](https://app.circleci.com/pipelines/github/dbt-msft/dbt-sqlserver/47/workflows/e06e2e39-13cf-4213-b401-015ee510f512/jobs/129) for the azuresql testing, because I ignorantly gave the azuresql target the same schema as is used for testing in the dbt-external-tables repo...
```
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop schema 'dbt_external_tables_integration_tests_azuresql' because it is being referenced by object 'people_csv_unpartitioned'. (3729) (SQLExecDirectW)")
```
let's see if this does anything for us.
=> HOTFIX break conflict w/ dbt-external-tables testing

dbt/include/sqlserver/macros/adapters.sql
fixes #85: @alangsbo's suggestion for situations when the server and database have different collations set.
=> collate tempdb columns to db default

dbt/adapters/sqlserver/connections.py
My bad for directing us to the wrong docs in #63. Instead of `APP` we want `Application Name`. From Synapse PM:
> On the application name parameter, for ODBC, please use “Application Name=dbt-{credentials.type}” (per your example). The key here is the parameter being “Application Name” with a space between Application and Name. If you happen to use JDBC, then you can use applicationName (no space).  
While we're here, I figure it can't hurt to send the `dbt-sqlserver` version as well.
=> Update application name ODBC parameter

.circleci/config.yml, CHANGELOG.md, test/integration/azuresql.dbtspec, test/integration/dbt_project.yml
Azure SQL Standard Tier is more expensive than hopefully needed. To make Azure SQL serverless work, I:
- disabled the default `columnstore` option, and
- made the `connection-azuresql` job come before the `integration-azuresql` job to ensure that the serverless db is unpaused/active before connecting
=> Hotfix  serverless sql

CHANGELOG.md, dbt/adapters/sqlserver/impl.py
=> fix for empty seed tables

dbt/adapters/sqlserver/connections.py
drop unneeded debugging code that only was run when "Active Directory integrated" was given as the auth method
fixes: #148
=> drop unecessary& broken code from ADIntegrated connection option

dbt/include/sqlserver/macros/adapters.sql
resolves [dbt-synapse](https://github.com/dbt-msft/dbt-synapse) [issue 152](https://github.com/dbt-msft/dbt-sqlserver/issues/152) incremental table alter column type syntax error
=> add sqlserver__alter_column_type macro

dbt/include/sqlserver/macros/indexes.sql
if columns contains space then index name built from the name contains space as well. Fixed with space replaced to underscore.
=> fix index with columns containing spaces

.circleci/config.yml
I don't have any experience with Circle CI, but the point is that it should have the same env vars set as in the check above.
=> set env vars explicitly to fix circle ci check

.github/workflows/integration-tests-azure.yml, .github/workflows/integration-tests-sqlserver.yml
CI tests were failing on PRs from external contributors because the secrets were not available
this changes that so that the tests without secrets always run and the tests needing secrets are only triggered when you add the label `safe to test`
=> run CI tests on trusted PRs and include secrets

dbt/include/sqlserver/macros/adapters/indexes.sql
remove spaces and dot in index name, add qoutes around schema and table name when creating or dropping index
=> Fix #213 - dbt test error when source name contains spaces and/or dots

.github/workflows/integration-tests-azure.yml, .github/workflows/integration-tests-sqlserver.yml, Makefile, dbt/adapters/sqlserver/sql_server_credentials.py, dbt/include/sqlserver/macros/adapters/apply_grants.sql, pytest.ini, tests/conftest.py, tests/functional/adapter/test_provision_users.py
This would automatically provision Azure AD users used in grants if they are not created in the database yet. This is using contained database users which would only be possible in Azure SQL and Azure Synapse.
=> Automatically provision Azure AD users if enabled

setup.py
allow newer pyodbc versions but exclude the broken 4.0.34
=> allow newer pyodbc versions

.github/workflows/publish-docker.yml
this would allow anyone to publish images on the same tags, disrupting the workflows on master
=> avoid publishing docker from other branches than master

CHANGELOG.md, dbt/adapters/sqlserver/__version__.py, dev_requirements.txt, setup.py
This is a bugfix 1.3.2 release, it resolves #348.
As we already have an ongoing v1.4 release on master, this PR requires a v1.3 branch to be created from the v.1.3.1 tag, which I do not think I can do myself. @dataders @sdebruyn can you help with this?
=> bugfix: Install a correct version of `dbt-core` that is compatible with the library

dbt/include/sqlserver/macros/adapters/columns.sql, dbt/include/sqlserver/macros/adapters/relation.sql, dbt/include/sqlserver/macros/materializations/models/table/create_table_as.sql, dbt/include/sqlserver/macros/materializations/models/view/create_view_as.sql, tests/functional/adapter/test_basic.py
- should fix all the concurrency issues we currently experience (deadlocks)
- stick a bit closer to the upstream/core macros where possible
=> Fix concurrency issues and document create as

dbt/adapters/sqlserver/sql_server_column.py, dbt/include/sqlserver/macros/adapters/columns.sql, dbt/include/sqlserver/macros/materializations/models/incremental/merge.sql, tests/functional/adapter/test_incremental.py, tests/functional/adapter/test_seed.py
need to look at:
resolves #338
resolves #217
resolves #333
resolves #133
resolves #326
=> [incremental models] add tests, various bugfixes and support for incremental predicates

dbt/adapters/sqlserver/sql_server_adapter.py, dbt/adapters/sqlserver/sql_server_credentials.py, dbt/include/sqlserver/macros/adapters/schema.sql, tests/conftest.py, tests/functional/adapter/test_schema.py
Based on #277 
- add tests
- make it work
Resolves #153
=> Add schema authorization config

dbt/include/sqlserver/macros/adapters/indexes.sql
=> use MD5 hashing to avoid long index names

dbt/adapters/sqlserver/sql_server_connection_manager.py, tests/unit/adapters/sqlserver/test_sql_server_connection_manager.py
Fixes #253, supercedes #254
pyodbc is unlikley to include a handler for DATETIMEOFFSET data types - see [mkleehammer/pyodbc#134](https://github.com/mkleehammer/pyodbc/issues/134).
So, this PR adds support to convert these datatypes to standard `datetime` objects based on public MS documentation.
This should allow [freshness](https://docs.getdbt.com/reference/resource-properties/freshness) functonality to use DATETIMEOFFSET columns without needing to use CAST/CONVERT in [loaded_at_field](https://docs.getdbt.com/reference/resource-properties/freshness#loaded_at_field) resource properties.
Tests are against `str(value: datetime)` default string format, since this asserts compatibility with:
- [innoverio.vscode-dbt-power-user](https://github.com/innoverio/vscode-dbt-power-user)'s query …
=> fix: adds pyodbc output converter for DATETIMEOFFSET data types

dbt/adapters/sqlserver/sql_server_connection_manager.py, dbt/adapters/sqlserver/sql_server_credentials.py
resolves #162
we will have to add this in the docs as well
=> Add support for timeout options

dbt/include/sqlserver/macros/adapter/indexes.sql, dbt/include/sqlserver/macros/materializations/tests.sql, tests/functional/adapter/mssql/test_index.py, tests/functional/adapter/mssql/test_test_with.py
Updated version of this PR to drop schemas on a target table in a target schema.
Current behaviour drops the indexes on all tables that match the target, regardless of schema.
https://github.com/dbt-msft/dbt-sqlserver/pull/439
Closes issue https://github.com/dbt-msft/dbt-sqlserver/issues/519
=> Update drop all schemas to target only schemas of a table in a given index

dbt/include/sqlserver/macros/materializations/tests.sql, tests/functional/adapter/mssql/test_test_with.py
Switches from searching for `with` at the beginning of the `main_sql` statement, to searching for `with ... as (` using regex
Added tests to validate behaviour of using `with` statements in custom tests including statements that begin with comments
Address issue https://github.com/dbt-msft/dbt-sqlserver/issues/470
=> updated behaviour of custom tests using with statements

dbt/include/sqlserver/macros/relations/table/create.sql, tests/functional/adapter/mssql/test_db_non_standard.py
Closing https://github.com/dbt-msft/dbt-sqlserver/issues/549 by updating to use proper `relation` instead of manually rendering.
Additionally adds test to validate behaviour.
=> updated create table logic for using proper dbt render

dbt/include/sqlserver/macros/adapter/catalog.sql
Resolves incorrect syntax near keyword error that I reported as an issue earlier as issue https://github.com/dbt-msft/dbt-sqlserver/issues/556
=> Fix incorrect syntax near keyword 'as' in catalog creation

.devcontainer/devcontainer-lock.json, .devcontainer/devcontainer.json, .gitignore, CHANGELOG.md, dbt/adapters/sqlserver/__version__.py, dbt/include/sqlserver/macros/materializations/tests.sql, tests/functional/adapter/mssql/test_test_with.py
Fixes broken tests and bumps version for release
=> 560 test code reporting error when test code uses ctes with line breaks after with keyword

.pre-commit-config.yaml, tests/functional/adapter/dbt/test_simple_seed.py
Update test definition to match upstream Fabric adapater as we cannot currently pass the test.
=> Resolves #588

dbt/include/sqlserver/macros/materializations/tests.sql, dbt/include/sqlserver/macros/materializations/unit_tests.sql
Resolves #575 Use the local MD5 macro to create a more unique hash based on the SQL of the test itself
=> Update the derivation of the test view name

.github/workflows/integration-tests-sqlserver.yml, .github/workflows/publish-docker.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, dbt/adapters/sqlserver/__version__.py, dbt/adapters/sqlserver/sqlserver_adapter.py, dbt/adapters/sqlserver/sqlserver_relation.py, dbt/include/sqlserver/dbt_project.yml, dbt/include/sqlserver/macros/adapter/columns.sql, dbt/include/sqlserver/macros/materializations/models/incremental/merge.sql, dev_requirements.txt, setup.py, tests/functional/adapter/dbt/test_empty.py, tests/functional/adapter/dbt/test_incremental.py, tests/functional/adapter/dbt/test_incremental_microbatch_datetime.py
Closes #597.
All the tests appear to pass and I've successfully used the micro batch functionality locally using this version of the adapter. If anyone can think of additional tests that we require I can look at adding them but the Fabric adapter seemed to have the new functionality covered.
=> Update to 1.9
